#!/bin/sh
#
# Display PitLab Wallet splash screen on tty1
#

SPLASH_SCRIPT=/usr/local/bin/pitlab-wallet-splash.sh

start() {
    printf "Displaying splash screen: "
    $SPLASH_SCRIPT
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    # Nothing to stop for oneshot splash
    :
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
